version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "uploads:/root/.castyou"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: "database"
    ports:
      - 80
    restart: always
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "database:/var/lib/postgresql/data"

volumes:
  database:
  uploads:
