version: "2.1"

services:
  web:
    image: nginx
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      API_URL: ${API_URL}
    volumes:
      - "./nginx:/etc/nginx/conf.d:ro"
      - "uploads:/usr/share/nginx/podcasts:ro"
    ports:
      - "8888:80"
    depends_on:
      - ui
      - backend

  ui:
    image: node:8-alpine
    working_dir: /app
    command: "/app/dev-server.sh"
    volumes:
      - "./ui:/app"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      API_URL: ${API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "uploads:/root/.castyou"
      - ".:/app"
    environment:
      STATIC_URL: ${STATIC_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: "database"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "database:/var/lib/postgresql/data"

volumes:
  database:
  uploads:
