version: "2.1"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: castyou
      POSTGRES_DB: castyou
      POSTGRES_PASSWORD: castyou
    restart: always
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "database:/var/lib/postgresql/data"

volumes:
  database:
